### ISSUE TITLE
horizontal scrollbar when changing slide

### ISSUE THREAD

**Issue by simonlopez** [worldline/angularjs-sdco-slides#1]
Hi,
In the provide example, when changing slides, there is an horizontal scrollbar that appears and then disappears.

**Comment by rlegrand** [comment]
Yes, it's fixed on master and on the sample, so ok for next release (1.0.1)

**Comment by maxired** [comment]
On the current sample, the left 'border' moves up and down when changing slides. 
This in probably a related issue.

**Comment by rlegrand** [comment]
Both are related to stylesheets, but are a little bit different.
Anyway, it should be fine now for these problems.
